GET http://localhost:8080/api/guitar
Content-Type: application/json

###
GET http://localhost:8080/api/guitar?id=2

###
POST http://localhost:8080/api/guitar
Content-Type: application/json
{
  "make": "Taylor",
  "model": "914"
}

###
GET http://localhost:8080/api/item/2

###
GET http://localhost:8080/api/item?id=5

###
GET http://localhost:8080/notSupported

###
