GET http://localhost:8080/api/people
Content-Type: application/json

###
GET http://localhost:8080/api/people?pin=1

###
GET http://localhost:8080/api/people/1

###
POST http://localhost:8080/api/people
Content-Type: application/json

{
  "pin": 4,
  "name": "Hung Phan"
}

###
